version: '3'

services:
  gokit:
    image: registry-vpc.cn-beijing.aliyuncs.com/tiyee/gokit:latest
    container_name: gokit
    command:  /app/gokit
    restart: on-failure
    ports:
      - "127.0.0.1:4718:4718"
    expose:
      - "4718"
    volumes:
      - /data/logs/gokit/:/app/logs/ 
